#!/bin/bash

install_path=$1
mcmodule=$(cat ./requirements.txt)
if [[ $mcmodule == *@* ]]; then
    mcbranch="--branch ${mcmodule/*@/}"
    mcmodule=${mcmodule/@*/}
else
    mcbranch=""
fi
mcurl=${mcmodule/git+/}
mcname=$(basename $mcmodule)
mcname=${mcname/.git/}
[[ -f ${install_path}/mirgecom/setup.py ]] || git clone --recursive ${mcbranch} ${mcurl} ${install_path}/mirgecom
