#!/bin/bash

set -o nounset -o errexit

package_directory=$2
specific_package=$3
if [[ $1 !=  "-x" ]]; then
    echo "WARNING: This script is for advanced users only. It updates the emirge"
    echo "pip packages."
    echo "Execute this script with the '-x' option if you want to run it: '$0 -x'"
    echo "Exiting."
    exit 1
fi
if [ -z "${specific_package}" ]; then specific_package="*"; fi
if [ ! -d "${package_directory}" ]
then
    printf "Target directory (${package_directory}) does not exist.\n"
    exit 1
fi
running_directory=`pwd`

for m in ${package_directory}/${specific_package}/; do
    # Skip non-git directories
    [[ -d $m/.git/ ]] || continue

    cd $m

    echo "=== Updating $m"

    # Skip directories that have local modifications
    git diff-index --quiet HEAD || { echo "  Skipping update of '$m' due to local modifications."; cd ${running_directory}; continue; }

    git pull

    cd ${running_directory}
done

echo "==== Pulled updated modules."
