name: ShellCheck

# See https://github.com/koalaman/shellcheck/wiki
# for explanations of ShellCheck error codes

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: ShellCheck
      run: shellcheck -x *.sh
