name: CI test

# Trigger the workflow on push
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install prerequisites
      run: ./install.sh
    - name: Run mirgelet
      run: cd mirgecom && python ./wave-eager.py
